config/routes.rb
Rails.application.routes.draw do
  resources :shoes

  get 'welcome/index'

  root  'shoes#index'

end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
    if params[:key]
      @shoe.picture_key = params[:key]
    else
      @shoe.picture.success_action_redirect = new_shoe_url
    end
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
            params.require(:shoe).permit(:name, :picture, :designer, :description, :color, :picture_key)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoeaddictApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
  <% if notice.present? %>
      <aside class="alert alert-info">
        <%= notice %>
      </aside>
  <% end %>
  <% if alert.present? %>
      <aside class="alert alert-danger">
        <%= alert %>
      </aside>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/shoes/_form.html.erb
# app/views/shoes/_form.html.erb

<% unless @shoe.has_picture_upload? %>
    <%= direct_upload_form_for(@shoe.picture) do |f| %>
        <div class="field">
          <%= f.label :picture %><br>
          <%= f.file_field :picture %>
        </div>
        <div class="actions">
          <%= f.submit 'Upload Picture'%>
        </div>
    <% end %>
<% else %>
    <%= "File \"#{File.basename(@shoe.picture_key)}\" has been uploaded to S3."%>
<% end %>

<%= form_for(@shoe, html: {:multipart => true}) do |f| %>
  <% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
        <% @shoe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :designer %><br>
    <%= f.text_field :designer %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>

  <%= f.hidden_field :picture_key %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<h1>Editing Shoe</h1>

<%= render 'form' %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
<p id="notice"><%= notice %></p>

<<h1>My Loving Shoes</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Designer</th>
      <th>Description</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoes.each do |shoe| %>
      <tr>
        <td><%= shoe.name %></td>
        <!-- <td><%= shoe.picture %> # Comment this line -->
  	<td>
	   <a href="<%= shoe.picture_url %>">
    	     <%= image_tag shoe.picture_url(:thumb) if shoe.picture? %>
  	   </a>
	</td> <!-- Add this line -->
        <td><%= shoe.designer %></td>
        <td><%= shoe.description %></td>
        <td><%= shoe.color %></td>
        <td><%= link_to 'Show', shoe %></td>
        <td><%= link_to 'Edit', edit_shoe_path(shoe) %></td>
        <td><%= link_to 'Destroy', shoe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shoe', new_shoe_path %>

app/views/shoes/new.html.erb
<h1>New Shoe</h1>

<%= render 'form' %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shoe.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@shoe.picture_url, :width => 600) if  @shoe.has_picture_upload? %>
</p>

<p>
  <strong>Designer:</strong>
  <%= image_tag(@shoe.picture_url, :width => 400) if @shoe.picture.present? %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shoe.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @shoe.color %>
</p>

<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%= link_to 'Back', shoes_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>